# Generated by Django 6.0.6 on 2026-06-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('College', 'College'), ('Pilgrimage', 'Pilgrimage'), ('Domestic', 'Domestic'), ('International', 'International'), ('Group Tour', 'Group Tour')], max_length=50)),
                ('cover_photo', models.URLField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('available_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('College', 'College'), ('Pilgrimage', 'Pilgrimage'), ('Domestic', 'Domestic'), ('International', 'International'), ('Group Tour', 'Group Tour')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=200)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('travel_mode', models.CharField(blank=True, choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Flight', 'Flight'), ('Coach', 'Coach'), ('Other', 'Other')], max_length=20, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('College', 'College'), ('Pilgrimage', 'Pilgrimage'), ('Domestic', 'Domestic'), ('International', 'International'), ('Group Tour', 'Group Tour')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.grouptrip')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Flight', 'Flight')], max_length=20)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.grouptrip')),
            ],
        ),
    ]
