# Generated by Django 6.0.6 on 2026-06-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptrip',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_trips/'),
        ),
    ]
